-- =============================================================================
-- NETRAVAAH — Hazard Intelligence Module
-- PostgreSQL Schema: hazard_schema.sql
-- Version: 1.0.0
-- Description: Complete schema for the Hazard Intelligence Module including
--              alerts, predictions, routes, shelters, sirens, resources, and events.
-- =============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- Migration Tracking
-- =============================================================================
CREATE TABLE IF NOT EXISTS schema_migrations (
  id          SERIAL       PRIMARY KEY,
  version     VARCHAR(50)  NOT NULL UNIQUE,
  description TEXT,
  applied_at  TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE schema_migrations IS 'Tracks applied schema migrations for the Hazard Intelligence Module.';

INSERT INTO schema_migrations (version, description)
VALUES ('1.0.0', 'Initial schema — Hazard Intelligence Module (9 tables + seed data)')
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- 1. hazard_alerts — Triggered alert log
-- =============================================================================
CREATE TABLE IF NOT EXISTS hazard_alerts (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  level            VARCHAR(10)  NOT NULL CHECK (level IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
  type             VARCHAR(30)  NOT NULL,
  district         VARCHAR(100) NOT NULL,
  message          TEXT         NOT NULL,
  source           VARCHAR(50)  DEFAULT 'system',
  acknowledged     BOOLEAN      DEFAULT FALSE,
  acknowledged_by  VARCHAR(100),
  acknowledged_at  TIMESTAMPTZ,
  expires_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ  DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  hazard_alerts              IS 'Real-time hazard alert log generated by sensor triggers, ML predictions, or operator input.';
COMMENT ON COLUMN hazard_alerts.level        IS 'Severity level: GREEN | YELLOW | ORANGE | RED';
COMMENT ON COLUMN hazard_alerts.type         IS 'Alert type, e.g. FLOOD, LANDSLIDE, CYCLONE, HEAT_WAVE';
COMMENT ON COLUMN hazard_alerts.source       IS 'Originating subsystem or operator ID';
COMMENT ON COLUMN hazard_alerts.acknowledged IS 'TRUE once an operator has reviewed and acknowledged the alert';

-- =============================================================================
-- 2. flood_predictions — Cached ML outputs for flood risk
-- =============================================================================
CREATE TABLE IF NOT EXISTS flood_predictions (
  id                      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  district                VARCHAR(100) NOT NULL,
  rainfall                NUMERIC(8,2),
  river_level             NUMERIC(6,2),
  dam_discharge           NUMERIC(12,2),
  soil_moisture           NUMERIC(5,2),
  humidity                NUMERIC(5,2),
  historical_flood_index  NUMERIC(4,2),
  flood_probability       NUMERIC(5,4) NOT NULL,
  expected_water_level    NUMERIC(6,2),
  severity                VARCHAR(20)  NOT NULL CHECK (severity IN ('LOW', 'MODERATE', 'HIGH', 'EXTREME')),
  confidence_score        NUMERIC(5,4),
  model_source            VARCHAR(20)  DEFAULT 'rule_engine' CHECK (model_source IN ('ml_model', 'rule_engine')),
  timeline_json           JSONB,
  affected_regions_json   JSONB,
  created_at              TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  flood_predictions                    IS 'Stores flood probability predictions computed by the ML model or rule engine (Module 05).';
COMMENT ON COLUMN flood_predictions.rainfall           IS 'Input: rainfall in mm/hr';
COMMENT ON COLUMN flood_predictions.river_level        IS 'Input: river water level in meters';
COMMENT ON COLUMN flood_predictions.dam_discharge      IS 'Input: dam discharge in cusecs';
COMMENT ON COLUMN flood_predictions.flood_probability  IS 'Output: predicted flood probability [0.0, 1.0]';
COMMENT ON COLUMN flood_predictions.timeline_json      IS 'JSON array of FloodTimelineEntry objects (6h, 12h, 24h, 48h windows)';
COMMENT ON COLUMN flood_predictions.affected_regions_json IS 'JSON array of AffectedRegion objects';

-- =============================================================================
-- 3. landslide_predictions — Cached ML outputs for landslide risk
-- =============================================================================
CREATE TABLE IF NOT EXISTS landslide_predictions (
  id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  district              VARCHAR(100),
  rainfall              NUMERIC(8,2),
  terrain_slope         NUMERIC(5,2),
  soil_type             VARCHAR(20)  CHECK (soil_type IN ('CLAY', 'SANDY', 'LOAMY', 'ROCKY', 'MIXED')),
  vegetation_index      NUMERIC(4,3),
  risk_probability      NUMERIC(5,4) NOT NULL,
  alert_level           VARCHAR(10)  NOT NULL CHECK (alert_level IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
  evacuation_urgency    VARCHAR(20)  CHECK (evacuation_urgency IN ('NORMAL', 'WATCH', 'MONITOR', 'IMMEDIATE')),
  confidence_score      NUMERIC(5,4),
  affected_villages_json JSONB,
  model_source          VARCHAR(20)  DEFAULT 'rule_engine' CHECK (model_source IN ('ml_model', 'rule_engine')),
  created_at            TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  landslide_predictions                   IS 'Stores landslide risk assessments from the ML model or rule engine (Module 08).';
COMMENT ON COLUMN landslide_predictions.terrain_slope     IS 'Input: terrain slope angle in degrees [0, 90]';
COMMENT ON COLUMN landslide_predictions.vegetation_index  IS 'Input: NDVI-like index [0.0, 1.0]. Higher = more vegetation cover.';
COMMENT ON COLUMN landslide_predictions.risk_probability  IS 'Output: predicted landslide probability [0.0, 1.0]';
COMMENT ON COLUMN landslide_predictions.affected_villages_json IS 'JSON array of AffectedVillage objects with name, population, risk_score, distance';

-- =============================================================================
-- 4. evacuation_routes — Computed route plans
-- =============================================================================
CREATE TABLE IF NOT EXISTS evacuation_routes (
  id                      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  source                  VARCHAR(200) NOT NULL,
  destination             VARCHAR(200) NOT NULL,
  blocked_roads           JSONB        DEFAULT '[]',
  hazard_zones            JSONB        DEFAULT '[]',
  safest_path             JSONB        NOT NULL,
  travel_time_minutes     NUMERIC(8,2),
  distance_km             NUMERIC(8,2),
  safety_score            NUMERIC(5,2),
  algorithm               VARCHAR(20)  DEFAULT 'DIJKSTRA' CHECK (algorithm IN ('DIJKSTRA', 'ASTAR', 'DIJKSTRA+ASTAR')),
  alternative_routes_json JSONB,
  recommended_shelters_json JSONB,
  created_at              TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  evacuation_routes                    IS 'Stores computed evacuation route plans from Module 06 (Dijkstra / A*).';
COMMENT ON COLUMN evacuation_routes.safest_path        IS 'JSON array of node names representing the primary evacuation route';
COMMENT ON COLUMN evacuation_routes.safety_score       IS 'Route safety score [0, 100]. Penalised for hazard zone crossings.';
COMMENT ON COLUMN evacuation_routes.blocked_roads      IS 'JSON array of road/node names that were blocked during computation';
COMMENT ON COLUMN evacuation_routes.alternative_routes_json IS 'JSON array of RouteSegment objects for fallback paths';

-- =============================================================================
-- 5. shelters — Registered emergency shelters
-- =============================================================================
CREATE TABLE IF NOT EXISTS shelters (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name              VARCHAR(200) NOT NULL,
  district          VARCHAR(100) NOT NULL,
  address           TEXT,
  capacity          INTEGER      NOT NULL CHECK (capacity > 0),
  current_occupancy INTEGER      DEFAULT 0  CHECK (current_occupancy >= 0),
  status            VARCHAR(20)  DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'FULL', 'CLOSED', 'MAINTENANCE')),
  volunteers        INTEGER      DEFAULT 0,
  contact_number    VARCHAR(20),
  latitude          NUMERIC(10,7),
  longitude         NUMERIC(10,7),
  created_at        TIMESTAMPTZ  DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  DEFAULT NOW(),
  CONSTRAINT chk_occupancy_capacity CHECK (current_occupancy <= capacity)
);

COMMENT ON TABLE  shelters                  IS 'Registry of emergency shelters used during disaster response operations.';
COMMENT ON COLUMN shelters.capacity         IS 'Maximum number of evacuees the shelter can accommodate';
COMMENT ON COLUMN shelters.current_occupancy IS 'Current number of evacuees registered at the shelter';
COMMENT ON COLUMN shelters.status           IS 'Operational status: OPEN | FULL | CLOSED | MAINTENANCE';
COMMENT ON COLUMN shelters.volunteers       IS 'Number of active volunteers currently deployed at the shelter';

-- =============================================================================
-- 6. shelter_inventory — Per-shelter supply tracking
-- =============================================================================
CREATE TABLE IF NOT EXISTS shelter_inventory (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  shelter_id          UUID         NOT NULL REFERENCES shelters(id) ON DELETE CASCADE,
  item_type           VARCHAR(50)  NOT NULL CHECK (item_type IN ('FOOD', 'WATER', 'MEDICAL', 'CLOTHING', 'BLANKETS', 'OTHER')),
  quantity            NUMERIC(12,2) NOT NULL CHECK (quantity >= 0),
  unit                VARCHAR(30)  NOT NULL,
  days_remaining      NUMERIC(5,1),
  last_restocked_at   TIMESTAMPTZ,
  updated_at          TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  shelter_inventory                IS 'Tracks supply inventory at each shelter. Linked 1-to-many from shelters.';
COMMENT ON COLUMN shelter_inventory.item_type      IS 'Supply category: FOOD | WATER | MEDICAL | CLOTHING | BLANKETS | OTHER';
COMMENT ON COLUMN shelter_inventory.days_remaining IS 'Estimated number of days current stock will last at current consumption';

-- =============================================================================
-- 7. siren_systems — Emergency siren device registry
-- =============================================================================
CREATE TABLE IF NOT EXISTS siren_systems (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name              VARCHAR(200) NOT NULL,
  location          VARCHAR(300) NOT NULL,
  district          VARCHAR(100),
  zone              VARCHAR(50),
  coverage_km       NUMERIC(4,2),
  status            VARCHAR(20)  DEFAULT 'SILENT' CHECK (status IN ('ACTIVE', 'SILENT', 'OFFLINE', 'TESTING', 'MAINTENANCE')),
  last_activated_at TIMESTAMPTZ,
  last_tested_at    TIMESTAMPTZ,
  hardware_model    VARCHAR(100),
  created_at        TIMESTAMPTZ  DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  siren_systems             IS 'Registry of all emergency siren devices in the district network.';
COMMENT ON COLUMN siren_systems.zone        IS 'Operational zone identifier, e.g. ZONE-A, ZONE-B';
COMMENT ON COLUMN siren_systems.coverage_km IS 'Effective audible coverage radius in kilometers';
COMMENT ON COLUMN siren_systems.status      IS 'Current device status: ACTIVE | SILENT | OFFLINE | TESTING | MAINTENANCE';

-- =============================================================================
-- 8. resource_allocations — Deployment plans from Module 07
-- =============================================================================
CREATE TABLE IF NOT EXISTS resource_allocations (
  id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  district             VARCHAR(100) NOT NULL,
  population           INTEGER,
  threat_level         NUMERIC(4,2) CHECK (threat_level BETWEEN 1 AND 10),
  shelter_occupancy    NUMERIC(5,2) CHECK (shelter_occupancy BETWEEN 0 AND 100),
  trucks_needed        INTEGER,
  food_packets         INTEGER,
  water_required       INTEGER,
  medicines_required   INTEGER,
  priority_score       NUMERIC(5,2),
  critical_shortages   JSONB        DEFAULT '[]',
  deployment_plan_json JSONB,
  status               VARCHAR(30)  DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  created_at           TIMESTAMPTZ  DEFAULT NOW(),
  updated_at           TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  resource_allocations                  IS 'Stores computed resource deployment plans from Module 07 (Rule Engine).';
COMMENT ON COLUMN resource_allocations.threat_level     IS 'Input: threat level on scale 1–10';
COMMENT ON COLUMN resource_allocations.shelter_occupancy IS 'Input: percentage of shelter capacity currently occupied [0, 100]';
COMMENT ON COLUMN resource_allocations.priority_score   IS 'Computed priority urgency score [0, 100]';
COMMENT ON COLUMN resource_allocations.critical_shortages IS 'JSON array of shortage description strings';
COMMENT ON COLUMN resource_allocations.deployment_plan_json IS 'JSON array of DeploymentItem objects';
COMMENT ON COLUMN resource_allocations.status           IS 'Plan lifecycle status: PLANNED | IN_PROGRESS | COMPLETED | CANCELLED';

-- =============================================================================
-- 9. hazard_events — Audit log of all system events
-- =============================================================================
CREATE TABLE IF NOT EXISTS hazard_events (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type     VARCHAR(50)  NOT NULL,
  source_module  VARCHAR(50),
  district       VARCHAR(100),
  severity       VARCHAR(20),
  payload        JSONB,
  operator_id    VARCHAR(100),
  created_at     TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE  hazard_events              IS 'Immutable audit trail for all significant events across the Hazard Intelligence Module.';
COMMENT ON COLUMN hazard_events.event_type   IS 'Type of event, e.g. ALERT_TRIGGERED, SIREN_ACTIVATED, ROUTE_COMPUTED, PREDICTION_RUN';
COMMENT ON COLUMN hazard_events.source_module IS 'Module that generated the event, e.g. MODULE_05, MODULE_06, SIREN_CONTROL';
COMMENT ON COLUMN hazard_events.payload      IS 'Full JSON payload of the event for replay / debugging';
COMMENT ON COLUMN hazard_events.operator_id  IS 'ID of the operator who initiated the event (NULL for system-generated events)';

-- =============================================================================
-- Indexes
-- =============================================================================

-- hazard_alerts
CREATE INDEX IF NOT EXISTS idx_hazard_alerts_level      ON hazard_alerts(level);
CREATE INDEX IF NOT EXISTS idx_hazard_alerts_district   ON hazard_alerts(district);
CREATE INDEX IF NOT EXISTS idx_hazard_alerts_created_at ON hazard_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hazard_alerts_acknowledged ON hazard_alerts(acknowledged) WHERE acknowledged = FALSE;

-- flood_predictions
CREATE INDEX IF NOT EXISTS idx_flood_predictions_district ON flood_predictions(district);
CREATE INDEX IF NOT EXISTS idx_flood_predictions_severity ON flood_predictions(severity);
CREATE INDEX IF NOT EXISTS idx_flood_predictions_created  ON flood_predictions(created_at DESC);

-- landslide_predictions
CREATE INDEX IF NOT EXISTS idx_landslide_district    ON landslide_predictions(district);
CREATE INDEX IF NOT EXISTS idx_landslide_alert_level ON landslide_predictions(alert_level);
CREATE INDEX IF NOT EXISTS idx_landslide_created     ON landslide_predictions(created_at DESC);

-- shelters
CREATE INDEX IF NOT EXISTS idx_shelters_district ON shelters(district);
CREATE INDEX IF NOT EXISTS idx_shelters_status   ON shelters(status);

-- shelter_inventory
CREATE INDEX IF NOT EXISTS idx_shelter_inventory_shelter_id ON shelter_inventory(shelter_id);
CREATE INDEX IF NOT EXISTS idx_shelter_inventory_item_type  ON shelter_inventory(item_type);

-- siren_systems
CREATE INDEX IF NOT EXISTS idx_siren_status   ON siren_systems(status);
CREATE INDEX IF NOT EXISTS idx_siren_zone     ON siren_systems(zone);
CREATE INDEX IF NOT EXISTS idx_siren_district ON siren_systems(district);

-- resource_allocations
CREATE INDEX IF NOT EXISTS idx_resource_district ON resource_allocations(district);
CREATE INDEX IF NOT EXISTS idx_resource_status   ON resource_allocations(status);
CREATE INDEX IF NOT EXISTS idx_resource_created  ON resource_allocations(created_at DESC);

-- hazard_events
CREATE INDEX IF NOT EXISTS idx_hazard_events_type     ON hazard_events(event_type);
CREATE INDEX IF NOT EXISTS idx_hazard_events_district ON hazard_events(district);
CREATE INDEX IF NOT EXISTS idx_hazard_events_created  ON hazard_events(created_at DESC);

-- =============================================================================
-- Seed Data — Siren Systems
-- =============================================================================
INSERT INTO siren_systems (name, location, district, zone, coverage_km, status)
VALUES
  ('Mula-Mutha Confluence Siren', 'Sangam Bridge, Pune',               'Pune Central', 'ZONE-A', 2.5, 'ACTIVE'),
  ('Sector 4 Emergency Mast',     'Sector 4 Sports Ground, Pune',       'Pune East',    'ZONE-B', 3.0, 'SILENT'),
  ('Hill Slope Early Warning Siren','Katraj Ghats',                     'Pune South',   'ZONE-C', 1.5, 'SILENT'),
  ('Civic HQ Central Alarm',       'Municipal Corporation Plaza',        'Pune Central', 'ZONE-A', 5.0, 'OFFLINE'),
  ('Hadapsar Industrial Siren',    'Hadapsar Industrial Estate',         'Hadapsar',     'ZONE-D', 2.0, 'SILENT')
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Seed Data — Shelters
-- =============================================================================
INSERT INTO shelters (name, district, address, capacity, current_occupancy, status, volunteers, latitude, longitude)
VALUES
  ('Bal Gandharva Shelter Camp',   'Pune Central', 'Bal Gandharva Rang Mandir Complex',       500,  340, 'OPEN',       24, 18.5196, 73.8553),
  ('Nehru Stadium Relief Centre',  'Shivajinagar', 'Nehru Stadium Complex, Shivajinagar',     800,  720, 'OPEN',       42, 18.5308, 73.8475),
  ('Hadapsar Sports Complex',      'Hadapsar',     'Hadapsar Sports Complex, East Pune',      400,  120, 'OPEN',       18, 18.5018, 73.9257),
  ('Katraj Community Hall',        'Katraj',       'Katraj Community Hall, Satara Road',      250,  250, 'FULL',        8, 18.4529, 73.8687)
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Seed Data — Shelter Inventory
-- =============================================================================
INSERT INTO shelter_inventory (shelter_id, item_type, quantity, unit, days_remaining)
SELECT id, 'FOOD',    2400,  'packets', 4 FROM shelters WHERE name = 'Bal Gandharva Shelter Camp'
UNION ALL
SELECT id, 'WATER',  50000, 'liters',  6 FROM shelters WHERE name = 'Bal Gandharva Shelter Camp'
UNION ALL
SELECT id, 'MEDICAL',   80, 'kits',    8 FROM shelters WHERE name = 'Bal Gandharva Shelter Camp'
UNION ALL
SELECT id, 'FOOD',    1440,  'packets', 2 FROM shelters WHERE name = 'Nehru Stadium Relief Centre'
UNION ALL
SELECT id, 'WATER',  30000, 'liters',  3 FROM shelters WHERE name = 'Nehru Stadium Relief Centre'
UNION ALL
SELECT id, 'MEDICAL',  120, 'kits',    5 FROM shelters WHERE name = 'Nehru Stadium Relief Centre'
UNION ALL
SELECT id, 'FOOD',     960,  'packets', 7 FROM shelters WHERE name = 'Hadapsar Sports Complex'
UNION ALL
SELECT id, 'WATER',  15000, 'liters',  9 FROM shelters WHERE name = 'Hadapsar Sports Complex'
ON CONFLICT DO NOTHING;

-- =============================================================================
-- End of hazard_schema.sql
-- =============================================================================
