'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
  BookOpen, 
  Search, 
  MessageSquare, 
  FileText, 
  ChevronRight, 
  ShieldCheck, 
  ArrowRight,
  TrendingUp,
  Coins,
  Building,
  CheckCircle,
  Clock,
  ExternalLink
} from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { useUiStore } from '@/store/useUiStore';
import { cn } from '@/lib/utils';

interface Scheme {
  id: string;
  name: string;
  code: string;
  ministry: string;
  category: string;
  budget: string;
  beneficiaries: string;
  description: string;
  longDescription: string;
  status: 'Active' | 'Under Review' | 'Draft';
  launchYear: string;
  guidelines: { title: string; content: string }[];
  citations: string[];
}

const MOCK_SCHEMES: Scheme[] = [
  {
    id: 'scheme-1',
    name: 'National Digital Health Mission (NDHM)',
    code: 'MOHFW-NDHM-2026',
    ministry: 'Ministry of Health and Family Welfare',
    category: 'Healthcare & Technology',
    budget: '₹2,400 Cr',
    beneficiaries: '35+ Lakh Wards',
    description: 'Developing the backbone necessary to support the integrated digital health infrastructure of the country.',
    longDescription: 'The National Digital Health Mission (NDHM) aims to create a centralized system that connects medical practitioners, hospitals, diagnostic labs, and pharmacies. It establishes a secure Registry of Health IDs, Patient Consent Managers, and standardized Electronic Health Records (EHR) to facilitate seamless data exchange while ensuring absolute privacy and data sovereignty of citizens.',
    status: 'Active',
    launchYear: '2020 (Expanded 2026)',
    guidelines: [
      { title: 'Section 1.1: Scope & Framework', content: 'Establishment of a unified digital registry for all citizens. Each citizen receives a 14-digit Health ID mapping clinical histories securely.' },
      { title: 'Section 1.2: Consent Architecture', content: 'Data sharing is governed by explicit consent policies. Medical providers cannot query clinical records without a time-bound cryptographic token generated by the patient app.' },
      { title: 'Section 2.3: Interoperability Protocols', content: 'All diagnostic facilities and healthcare clinics must align with HL7 FHIR database standards to enable immediate records syncing.' }
    ],
    citations: [
      'G.S.R. 412(E) - Health Data Privacy Regulations 2024',
      'NDHM Guideline Memo V2.1 - Dec 2025',
      'National Health Policy Directive, Section 14-A'
    ]
  },
  {
    id: 'scheme-2',
    name: 'Jal Jeevan Mission (Urban & Rural)',
    code: 'MOWR-JJM-2026',
    ministry: 'Ministry of Jal Shakti',
    category: 'Infrastructure & Water',
    budget: '₹11,500 Cr',
    beneficiaries: '4.8 Cr Households',
    description: 'Providing Functional Household Tap Connections (FHTC) to all households in rural and urban sectors.',
    longDescription: 'The Jal Jeevan Mission is designed to assist, empower, and facilitate states in planning, designing, and executing participatory water supply schemes. The urban extension focuses on circular economy of water, recycling of greywater, sewage treatment plant (STP) integration, and rejuvenation of urban water bodies with automated flow sensors.',
    status: 'Active',
    launchYear: '2019 (Phase II 2026)',
    guidelines: [
      { title: 'Section 3.1: Supply Requirements', content: 'Every household must receive a minimum of 55 liters per capita per day (lpcd) of potable drinking water at adequate pressure.' },
      { title: 'Section 3.2: Sensor Installation', content: 'IoT flow-rate meters must be embedded at district nodes to log distribution volumes, reporting leaks within 10 minutes to central dashboards.' },
      { title: 'Section 4.5: Quality Auditing', content: 'Bi-weekly chemical testing for fluoride, arsenic, and bacterial contaminants is mandatory at localized treatment nodes.' }
    ],
    citations: [
      'Water Supply Engineering Standard BIS 10500',
      'Jal Shakti Clean Water Act Directive 2023',
      'National Infrastructure Pipeline Report, Vol. III'
    ]
  },
  {
    id: 'scheme-3',
    name: 'Pradhan Mantri Awas Yojana (PMAY-U 2.0)',
    code: 'MOHUA-PMAY-2026',
    ministry: 'Ministry of Housing and Urban Affairs',
    category: 'Affordable Housing',
    budget: '₹8,200 Cr',
    beneficiaries: '1.2 Cr Wards',
    description: 'Providing all-weather pucca houses to eligible urban families with smart utility connections and solar roofing.',
    longDescription: 'PMAY-Urban 2.0 targets housing shortage among urban poor and middle-income groups. Houses built under this scheme incorporate green building standards, earthquake-resistant design, rainwater harvesting systems, and mandatory grid-tied rooftop solar panel arrays to lower household utility bills.',
    status: 'Active',
    launchYear: '2024 (Revised 2026)',
    guidelines: [
      { title: 'Section 2.1: Eligibility Matrices', content: 'Families with an annual income below ₹6,00,000 without a pucca house in their name anywhere in India qualify for the Credit Linked Subsidy.' },
      { title: 'Section 2.4: Green Infrastructure Mandate', content: 'All projects above 50 dwelling units must integrate solid waste processing facilities and 20% green ground cover area.' },
      { title: 'Section 3.1: Energy Retrofitting', content: 'Subsidized units receive priority net-metering solar arrays of 1kW minimum rating, directly synced to state grids.' }
    ],
    citations: [
      'Urban Development Strategy Paper, Sec 8.4',
      'National Building Code of India (NBC) 2025 Revision',
      'PMAY-U Smart Housing Directives, Order No. 44'
    ]
  },
  {
    id: 'scheme-4',
    name: 'Smart Agriculture & Soil Health Protocol',
    code: 'MOA-SASH-2026',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture & Technology',
    budget: '₹4,100 Cr',
    beneficiaries: '85 Lakh Farmers',
    description: 'Deploying localized IoT soil sensors, micro-sprinkling subsidies, and automated weather advisory systems.',
    longDescription: 'This protocol integrates localized crop advising with satellite imagery. Soil health analysis is translated into customized fertilizer recipes sent directly to farmers. Subsidies for drone spraying and drip-irrigation retrofits are disbursed based on telemetry data from these sensors.',
    status: 'Under Review',
    launchYear: '2025',
    guidelines: [
      { title: 'Section 1.2: Sensor Deployment Criteria', content: 'Farmers holding more than 2 hectares qualify for 80% subsidized IoT probes transmitting NPK and moisture levels.' },
      { title: 'Section 2.3: Crop Rotation Directives', content: 'Mandatory rotation guidelines for water-intensive cash crops in high-stress aquifers to restore soil fertility.' }
    ],
    citations: [
      'Agricultural Land Preservation Act 2024',
      'Aquifer Overdraft Containment Policy, Rule 12B',
      'State Soil Lab Accreditation Code'
    ]
  }
];

export default function PolicyDashboard() {
  const { setActiveTab } = useUiStore();
  const [selectedSchemeId, setSelectedSchemeId] = useState<string>(MOCK_SCHEMES[0].id);
  const [searchQuery, setSearchQuery] = useState<string>('');

  useEffect(() => {
    setActiveTab('Policy Intelligence');
  }, [setActiveTab]);

  const filteredSchemes = MOCK_SCHEMES.filter(scheme =>
    scheme.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    scheme.ministry.toLowerCase().includes(searchQuery.toLowerCase()) ||
    scheme.code.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const selectedScheme = MOCK_SCHEMES.find(s => s.id === selectedSchemeId) || MOCK_SCHEMES[0];

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
      
      {/* 1. Page Header & Navigation Tabs */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-5">
        <div>
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-blue-600 dark:bg-emerald-500 animate-pulse" />
            <span className="text-[10px] uppercase tracking-widest text-blue-900 dark:text-brand-yellow font-bold">
              National Policy Intelligence Portal
            </span>
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 dark:text-slate-100 mt-1">
            Policy Intelligence Module
          </h1>
          <p className="text-slate-800 dark:text-slate-400 text-sm mt-0.5 font-medium">
            Search federal schemes, retrieve legislative documents, and query the RAG Policy Chat.
          </p>
        </div>

        {/* Sub Navigation Tabs */}
        <div className="flex items-center gap-2 bg-slate-100 dark:bg-slate-900 p-1 rounded-xl border border-slate-200 dark:border-slate-800">
          <Link href="/policies" className="px-4 py-2 text-xs font-bold rounded-lg bg-white dark:bg-slate-800 text-blue-950 dark:text-white shadow-xs border border-slate-200 dark:border-slate-700">
            📚 Catalog
          </Link>
          <Link href="/policies/search" className="px-4 py-2 text-xs font-bold rounded-lg text-slate-900 hover:text-blue-900 dark:text-slate-400 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-800 transition-all">
            🔍 Advanced Search
          </Link>
          <Link href="/policies/chat" className="px-4 py-2 text-xs font-bold rounded-lg text-slate-900 hover:text-blue-900 dark:text-slate-400 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-800 transition-all">
            💬 RAG Chat
          </Link>
        </div>
      </div>

      {/* 2. Key Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="bg-card border-border shadow-2xs">
          <CardContent className="p-4 flex items-center gap-4">
            <div className="p-3 bg-blue-100 dark:bg-blue-950 rounded-xl text-blue-900 dark:text-blue-400">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <p className="text-[10px] uppercase font-bold tracking-wider text-slate-900 dark:text-slate-400">Total Cataloged Schemes</p>
              <h3 className="text-xl font-extrabold text-blue-950 dark:text-white">142 Schemes</h3>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-2xs">
          <CardContent className="p-4 flex items-center gap-4">
            <div className="p-3 bg-emerald-100 dark:bg-emerald-950 rounded-xl text-emerald-900 dark:text-emerald-400">
              <Coins className="w-5 h-5" />
            </div>
            <div>
              <p className="text-[10px] uppercase font-bold tracking-wider text-slate-900 dark:text-slate-400">Active Budget Pool</p>
              <h3 className="text-xl font-extrabold text-emerald-950 dark:text-white">₹42,800 Cr</h3>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-2xs">
          <CardContent className="p-4 flex items-center gap-4">
            <div className="p-3 bg-purple-100 dark:bg-purple-950 rounded-xl text-purple-900 dark:text-purple-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <p className="text-[10px] uppercase font-bold tracking-wider text-slate-900 dark:text-slate-400">Indexed Clauses</p>
              <h3 className="text-xl font-extrabold text-purple-950 dark:text-white">18,450 Docs</h3>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-2xs">
          <CardContent className="p-4 flex items-center gap-4">
            <div className="p-3 bg-amber-100 dark:bg-amber-950 rounded-xl text-amber-950 dark:text-amber-400">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <p className="text-[10px] uppercase font-bold tracking-wider text-slate-900 dark:text-slate-400">Audit Status</p>
              <h3 className="text-xl font-extrabold text-amber-900 dark:text-white">Fully Certified</h3>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* 3. Main Split Panel: Schemes List & Document Viewer */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Directory / Catalog List (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          <div className="relative">
            <Search className="absolute left-3.5 top-3 h-4 w-4 text-slate-900 dark:text-slate-500" />
            <input
              type="text"
              placeholder="Search scheme name, ministry, or code..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-card border border-border rounded-xl text-sm text-slate-950 dark:text-white placeholder-slate-500 focus:outline-hidden focus:ring-2 focus:ring-blue-600 dark:focus:ring-emerald-500"
            />
          </div>

          <div className="space-y-3 overflow-y-auto max-h-[580px] pr-1">
            {filteredSchemes.map((scheme) => (
              <button
                key={scheme.id}
                onClick={() => setSelectedSchemeId(scheme.id)}
                className={cn(
                  "w-full text-left p-4 rounded-xl border transition-all cursor-pointer flex flex-col justify-between hover:bg-slate-50 dark:hover:bg-slate-900/50 shadow-2xs",
                  selectedSchemeId === scheme.id
                    ? "bg-blue-50/70 border-blue-600 dark:bg-slate-900 dark:border-emerald-500 ring-2 ring-blue-600/10 dark:ring-emerald-500/10"
                    : "bg-card border-border"
                )}
              >
                <div>
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-[9px] font-mono font-bold bg-slate-200 dark:bg-slate-800 text-slate-900 dark:text-slate-350 px-2 py-0.5 rounded border border-border">
                      {scheme.code}
                    </span>
                    <span className={cn(
                      "text-[9px] font-bold px-2 py-0.5 rounded-full border",
                      scheme.status === 'Active' 
                        ? 'bg-emerald-100 text-emerald-950 border-emerald-300 dark:bg-emerald-950/20 dark:text-emerald-400 dark:border-emerald-500/30'
                        : 'bg-amber-100 text-amber-950 border-amber-300 dark:bg-amber-950/20 dark:text-amber-400 dark:border-amber-500/30'
                    )}>
                      {scheme.status}
                    </span>
                  </div>

                  <h3 className="text-sm font-extrabold text-slate-950 dark:text-slate-100 mt-2.5 leading-snug">
                    {scheme.name}
                  </h3>
                  <p className="text-xs text-slate-900 dark:text-slate-400 font-medium mt-1">
                    {scheme.ministry}
                  </p>
                  <p className="text-xs text-slate-800 dark:text-slate-400 mt-2 line-clamp-2 leading-relaxed">
                    {scheme.description}
                  </p>
                </div>

                <div className="mt-4 pt-3 border-t border-slate-250 dark:border-slate-800 flex justify-between items-center text-[10px] font-bold">
                  <div className="flex items-center gap-1.5 text-slate-900 dark:text-slate-400">
                    <Coins className="w-3.5 h-3.5 text-blue-900 dark:text-emerald-500" />
                    <span>Budget: {scheme.budget}</span>
                  </div>
                  <div className="flex items-center gap-1 text-blue-900 dark:text-emerald-400">
                    <span>Inspect Document</span>
                    <ChevronRight className="w-3 h-3" />
                  </div>
                </div>
              </button>
            ))}

            {filteredSchemes.length === 0 && (
              <div className="text-center py-12 text-slate-800 dark:text-slate-500 font-medium">
                No matching schemes cataloged in the system.
              </div>
            )}
          </div>
        </div>

        {/* Right Column: Premium Document Intelligence Viewer (7 cols) */}
        <div className="lg:col-span-7">
          <Card className="h-full border-border bg-card shadow-sm flex flex-col overflow-hidden">
            
            {/* Doc Viewer Top Bar */}
            <div className="px-6 py-4 bg-slate-100 dark:bg-slate-900 border-b border-border flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <FileText className="w-5 h-5 text-blue-900 dark:text-emerald-500" />
                <div>
                  <h2 className="text-xs uppercase font-extrabold tracking-widest text-slate-900 dark:text-slate-400">
                    Document Intelligence Viewer
                  </h2>
                  <p className="text-[10px] text-blue-900 dark:text-emerald-400 font-bold font-mono">
                    SECURED // {selectedScheme.code}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-emerald-500" />
                <span className="text-[10px] font-bold text-slate-900 dark:text-slate-400 font-mono">VERIFIED DATA</span>
              </div>
            </div>

            {/* Simulated Official Document Sheet */}
            <div className="flex-1 p-6 overflow-y-auto max-h-[580px] space-y-6 bg-white dark:bg-slate-950/40 relative">
              
              {/* Watermark Logo Background */}
              <div className="absolute inset-0 flex items-center justify-center opacity-[0.02] dark:opacity-[0.04] pointer-events-none select-none">
                <div className="w-96 h-96 border-8 border-slate-900 dark:border-white rounded-full flex items-center justify-center">
                  <span className="text-6xl font-black tracking-widest font-serif">GOVT OF INDIA</span>
                </div>
              </div>

              {/* Title Section */}
              <div className="text-center border-b-2 border-slate-200 dark:border-slate-850 pb-5">
                <p className="text-[10px] tracking-widest uppercase font-black text-slate-900 dark:text-slate-400">
                  OFFICIAL EXECUTIVE INSTRUCTION DIRECTIVE
                </p>
                <h1 className="text-lg font-black text-blue-950 dark:text-slate-100 mt-2 font-serif uppercase max-w-xl mx-auto">
                  {selectedScheme.name}
                </h1>
                <div className="flex justify-center items-center gap-4 mt-3 text-xs text-slate-900 dark:text-slate-400 font-medium">
                  <span>Launch Cycle: <strong>{selectedScheme.launchYear}</strong></span>
                  <span>•</span>
                  <span>Status: <strong className="text-emerald-600 dark:text-emerald-400">{selectedScheme.status}</strong></span>
                </div>
              </div>

              {/* Summary Description Section */}
              <div className="space-y-2">
                <h3 className="text-xs uppercase font-extrabold text-blue-950 dark:text-emerald-500 tracking-wider">
                  I. Abstract & Legislative Objective
                </h3>
                <p className="text-xs text-slate-950 dark:text-slate-350 leading-relaxed font-sans text-justify">
                  {selectedScheme.longDescription}
                </p>
              </div>

              {/* Specific Policy Guidelines Sections */}
              <div className="space-y-4">
                <h3 className="text-xs uppercase font-extrabold text-blue-950 dark:text-emerald-500 tracking-wider">
                  II. Implementation Guidelines & Sub-clauses
                </h3>
                <div className="space-y-3">
                  {selectedScheme.guidelines.map((guide, idx) => (
                    <div key={idx} className="p-3 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-lg">
                      <h4 className="text-xs font-extrabold text-slate-950 dark:text-slate-200">
                        {guide.title}
                      </h4>
                      <p className="text-xs text-slate-900 dark:text-slate-450 mt-1 leading-relaxed font-medium">
                        {guide.content}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Official Citations Section */}
              <div className="space-y-3 pt-2">
                <h3 className="text-xs uppercase font-extrabold text-blue-950 dark:text-emerald-500 tracking-wider">
                  III. References & Statutory Citations
                </h3>
                <ul className="space-y-1.5 pl-5 list-disc text-xs text-slate-900 dark:text-slate-400 font-medium font-mono">
                  {selectedScheme.citations.map((cit, idx) => (
                    <li key={idx}>
                      {cit}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Seals and Authorization Footer */}
              <div className="border-t border-slate-250 dark:border-slate-850 pt-5 flex items-center justify-between">
                <div>
                  <p className="text-[8px] font-bold text-slate-800 dark:text-slate-500 uppercase tracking-widest">
                    Digital Approval ID
                  </p>
                  <p className="text-[10px] font-mono text-slate-900 dark:text-slate-400 font-bold mt-0.5">
                    SHA256-DIGITAL-STAMP-F89A4B
                  </p>
                </div>
                <div className="border border-slate-300 dark:border-slate-800 px-3 py-1.5 rounded bg-slate-50 dark:bg-slate-900 text-center select-none">
                  <span className="text-[9px] font-bold tracking-widest text-slate-900 dark:text-slate-400 uppercase font-mono">
                    APPROVED ARCHIVE
                  </span>
                </div>
              </div>
            </div>

            {/* Doc Viewer Bottom Button Panel */}
            <div className="px-6 py-4 bg-slate-100 dark:bg-slate-900 border-t border-border flex items-center justify-between">
              <Link
                href="/policies/chat"
                className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-lg transition-all shadow-xs dark:bg-emerald-600 dark:hover:bg-emerald-700 cursor-pointer"
              >
                <MessageSquare className="w-4 h-4" />
                <span>Query Document in Chat</span>
              </Link>
              
              <Link
                href="/policies/search"
                className="inline-flex items-center gap-1.5 text-xs font-bold text-blue-900 hover:text-blue-950 dark:text-slate-300 dark:hover:text-white transition-all cursor-pointer"
              >
                <span>Full Citations Index</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>

          </Card>
        </div>

      </div>

    </div>
  );
}
